// next or css
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Button from '@mui/material/Button';

// components
import InstagramIcon from '@mui/icons-material/Instagram';
import FacebookIcon from '@mui/icons-material/Facebook';
import AccessibilityNewIcon from '@mui/icons-material/AccessibilityNew';
import { Facebook } from '@mui/icons-material';
import EmailIcon from '@mui/icons-material/Email';

export default function Home() {
    var d = new Date().getFullYear(); 

    return (
        <div className={styles.container}>
            <Head>
                <title>WMFire</title>
                <meta name="description" content="Not generated by create next app" />
                <link rel="icon" href="/1.png" />
            </Head>

            <main className={styles.main} id="home">
                <div className={styles.home}>
                    <div className={styles.topBar}>

                        <img src="./logo.png" className={styles.topBarLogo} />
                        <p className={styles.topBarTitle}>WMFire</p>

                        <div className={styles.infoButtons}>
                            <Button sx={{ "&.MuiButton-text": { color: "black", fontSize: "1.3vw", fontFamily: "Montserrat" } }} href="#home" >Home</Button>
                            <Button sx={{ "&.MuiButton-text": { color: "black", fontSize: "1.3vw", fontFamily: "Montserrat" } }} href="#about" >About</Button>
                            <Button sx={{ "&.MuiButton-text": { color: "black", fontSize: "1.3vw", fontFamily: "Montserrat" } }} href="#resources" >Resources</Button>
                            <Button sx={{ "&.MuiButton-text": { color: "black", fontSize: "1.3vw", fontFamily: "Montserrat" } }} href="#contact" >Contact</Button>
                        </div>

                        <div>
                            <Button sx={{ "&.MuiButton-text": { color: "#000000" } }} href="https://www.facebook.com/FightingForImmigrantRightsandEquity/"><FacebookIcon sx={{ fontSize: "1.5vw" }} /></Button>
                            <Button sx={{ "&.MuiButton-text": { color: "#000000" } }} href="https://www.instagram.com/wmfire__/?hl=en"><InstagramIcon sx={{ fontSize: "1.5vw" }} /></Button>
                        </div>

                    </div>

                    <div className={styles.centerPiece}>
                        <div className={styles.slideshow}>
                            <img src="./undocuAlly.jpg" className={styles.image}></img>
                        </div>

                        <div className={styles.missionStatement}>
                            <div className={styles.smallMissionStatement}>
                                <p><AccessibilityNewIcon sx={{ fontSize: "1.5vw" }} /></p>
                                <p className={styles.statementText}>
                                    We at WMFIRE address the inequities and obstacles faced by the immigrant,
                                    migrant, and undocumented communities-at-large through education, empowerment,
                                    and action. Our mission is to gather information and resources, provide advocacy, and
                                    promote awareness of immigration issues to incite positive change. We center on
                                    making the W&amp;M community and beyond equitable for all, regardless of immigration
                                    status.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div className={styles.about} id="about">
                    <div className={styles.aboutPeople}>
                        <div className={styles.people}>
                            <div className={styles.person}></div>
                            <p className={styles.personInfo}>Hi, I&apos;m Person.</p>
                        </div>
                        <div className={styles.people}>
                            <div className={styles.person}></div>
                            <p className={styles.personInfo}>Hi, I&apos;m Person.</p>
                        </div>
                        <div className={styles.people}>
                            <div className={styles.person}></div>
                            <p className={styles.personInfo}>Hi, I&apos;m Person.</p>
                        </div>
                        <div className={styles.people}>
                            <div className={styles.person}></div>
                            <p className={styles.personInfo}>Hi, I&apos;m Person.</p>
                        </div>
                        <div className={styles.people}>
                            <div className={styles.person}></div>
                            <p className={styles.personInfo}>Hi, I&apos;m Person.</p>
                        </div>
                    </div>
                </div>

                <div className={styles.resources} id="resources">
                    <div className={styles.onCampusResources}>
                        <p className={styles.onCampusResourcesText}>
                            <b>On Campus Resources</b>
                        </p>
                        <p>
                            <b>WMFIRE</b> (WM Fighting For Immigrant Rights and Equity - This is us!) <br/>
                            We are more than happy to assist anyone in our community! We will do our best
                            to provide you with guidance and resources. If something is out of our reach, we
                            have connections on and off campus who may be able to help.
                        </p>
                        <p>
                            <b>Reves Center</b> <br/><br/>
                            The Reves Center works closely with the law firm McCandlish Holton of
                            Richmond to provide support and assistance to DACA students on campus.
                            Some services are free for W&amp;M students while others are offered at a reduced
                            rate. For more information, click on the link below. <br/><br/>
                            DACA Resource Hub <br/>
                            <a href="https://www.wm.edu/offices/sel/daca-support/resources/index.php">
                                https://www.wm.edu/offices/sel/daca-support/resources/index.php
                            </a>
                        </p>
                        <p>
                            <b>Center of Student Diversity</b> <br/><br/>
                            They focus on enhancing the experiences of students, particularly those of diverse
                            backgrounds. They work closely with many student-run organizations and other 
                            administrators in an attempt to improve our community. Feel free to visit them! <br/><br/>
                            <a href="https://www.wm.edu/offices/studentdiversity/">
                                https://www.wm.edu/offices/studentdiversity/
                            </a>
                            

                        </p>
                        <p>
                            <b>Counseling Center</b> <br/><br/>
                            Counseling sessions are free at the Wellness Center. If referring a student, 
                            know that there is a counselor with experience working with undocumented students. <br/><br/>
                            Dr. Carina Sudarsky-Gleiser

                        </p>
                        <p>
                            <b>W&amp;M Law School Immigration Clinic</b> <br/><br/>
                            The Immigration Clinic assists noncitizens with various immigration matters, 
                            including the citizenship and naturalization process. The Clinic also aids 
                            noncitizens seeking relief as victims of crime (U visa), domestic violence (VAWA), 
                            and human trafficking (T visa), as well as those currently held in detention seeking
                            release on bond. <br/><br/>
                            Contact: Prof. Stacy Kern-Scheerer <br/>
                            Email: sekernscheerer@wm.edu&emsp;&emsp;&emsp;Number: (757) 221-1460
                        </p>
                        <p>
                            <b>Dare To Dream Fund</b> (Funding for DACA renewals) <br/><br/>
                            Provides emergency support for students at W&amp;M with heightened vulnerability due 
                            to their immigration classification. Can be used for DACA Renewal Fees.<br/><br/>
                            To donate: <br/>
                            
                            <a href="https://giving.wm.edu/give-now/?appealcode=20N00&amp;allocation=4393">
                                https://giving.wm.edu/give-now/?appealcode=20N00&amp;allocation=4393
                            </a>
                             <br/><br/>
                            To request funds: <br/>
                            <a href="https://forms.wm.edu/form/view/41062/bee993cf06d8ce25611847e5b380a661">
                                https://forms.wm.edu/form/view/41062/bee993cf06d8ce25611847e5b380a661
                            </a>
                        </p>
                        <p>
                            <b>W&amp;M LatinX Alumni Jorge Alberto Urcuyo Scholarship</b><br/><br/>
                            Provides need-based scholarship support to students who are residents in the U.S. 
                            but whose immigration status or classification makes them ineligible to receive 
                            federal student aid, with a preference for those who have been granted Deferred Action 
                            for Childhood Arrivals (DACA) or Temporary Protected Status (TPS).
                        </p>
                        <p>
                            <b>Refugee Student Support Fund</b> <br/><br/>
                            Provides emergency support for students at William &amp; Mary with heightened vulnerability due 
                            to their refugee status. <br/><br/>
                            To Donate &amp; Learn More:<br/> 
                            <a href="https://giving.wm.edu/give-now/?appealcode=20N00&amp;allocation=4702">
                                https://giving.wm.edu/give-now/?appealcode=20N00&amp;allocation=4702
                            </a> <br/>
                            <a href="https://www.facebook.com/WMEmergencyFund/">
                                https://www.facebook.com/WMEmergencyFund/
                            </a>
                        </p>
                        <p>
                            <b>HEART Fund</b> <br/><br/>
                            The Health Emergency and Resources for the Tribe assists students experiencing financial hardships
                            due to extenuating circumstances. At the moment, it is providing aid in response to COVID-19. For
                            more information about how to donate or apply can be found in the link below: <br/><br/>
                            <a href="https://www.wm.edu/offices/deanofstudents/heartfund/index.php">
                                https://www.wm.edu/offices/deanofstudents/heartfund/index.php
                            </a>
                        </p>
                     </div>

                     <div className={styles.offCampusResources}>
                        <p className={styles.offCampusResourcesText}>
                            <b>Off Campus Resources</b>
                        </p>
                        <p>
                            <b>Dream Project and Mentoring Program</b> <br/><br/>
                            Non-profit organization in Arlington that encourages and supports promising immigrant youth in 
                            their pursuit of higher education through mentoring, scholarships, advocacy, and community outreach. <br/><br/>
                            <a href="https://www.dreamproject-va.org/mentoring/">
                                https://www.dreamproject-va.org/mentoring/
                            </a>
                        </p>
                        <p>
                        <b>Just Neighbors</b> <br/><br/>
                            provide immigration legal services to low-income immigrants and refugees of all faiths and nationalities, 
                            especially those who are most vulnerable. <br/><br/>
                            <a href="https://www.justneighbors.org/">
                                https://www.justneighbors.org/
                            </a>

                        </p>
                        <p>
                            <b>Legal Aid Justice Center</b> <br/><br/>
                            The Legal Aid Justice Center is committed to providing a full range of services to clients, 
                            including services our federal and state governments choose not to fund. Free Informational 
                            sessions at Mason for current students are currently under development. <br/><br/>
                            <a href="https://www.justice4all.org/">
                                https://www.justice4all.org/
                            </a>

                        </p>
                        <p>
                            <b>Ayuda</b> <br/><br/>
                            Serving immigrants in the Washington, DC, metropolitan region. Has 36 full-time, bilingual attorneys
                             and social workers/case managers providing legal, social, and language access services <br/><br/>
                            <a href="https://ayuda.com/">
                                https://ayuda.com/
                            </a>
                        </p>
                        <p>
                            <b>Capital Immigrant&apos;s Rights Coalition (CAIR)</b> <br/><br/>
                            Only legal service provider providing legal representation to detained 
                            Immigrants in facilities in DC, MD, and VA. <br/><br/>
                            <a href="https://www.immigrationadvocates.org/nonprofit/legaldirectory/organization.392734-Capital_Area_Immigrants_Rights_Coalition">
                                https://www.immigrationadvocates.org/nonprofit/legaldirectory/organization.392734-Capital_Area_Immigrants_Rights_Coalition
                            </a> 
                        </p>
                        <p>
                            <b>Tahirih Justice Center</b> <br/><br/>
                            The Tahirih Justice Center is a national nonprofit that has served over 25,000 courageous
                            individuals fleeing violence since 1997. Our efficient, effective, and innovative model
                            of service is now delivered from five locations, and we’re committed to serving as many
                            immigrant women and girls as possible. <br/><br/>
                            <a href="https://www.tahirih.org/">
                                https://www.tahirih.org/
                            </a>
                        </p>
                        <p>
                            <b>Edu-futuro</b> <br/><br/>
                            To empower immigrant and underserved youth and families through mentorship, education, leadership 
                            development and parent engagement. <br/><br/>
                            <a href="https://edu-futuro.org">
                                https://edu-futuro.org
                            </a>
                        </p>

                        <p className={styles.offCampusNotableText}>
                            <b>Notable Organizations:</b>
                        </p>
                        <p>
                            <b>Virginia Coalition of Latino Organizations (VACOLAO)</b> <br/><br/>
                            Serve as a working alliance among organizations in Virginia that serve or support the interest 
                            of the Latino communities. <br/><br/>
                            <a href="http://vacolao.org/">
                                http://vacolao.org/
                            </a>

                        </p>
                        <p>
                            <b>National Korean American Service &amp; Education Consortium (NAKASEC)</b> <br/><br/>
                            Grassroots organization founded in 1994 by local community centers to project a progressive voice 
                            and promote the full participation of Korean and Asian Americans within the larger society. <br/><br/>
                            <a href="https://nakasec.org/">
                                https://nakasec.org/
                            </a>
                        </p>
                        <p>
                            <b>The Virginia Latina Advocacy Network (VALAN)</b> <br/><br/>
                            operates as an extension of NLIRH, serving as the voice and advocacy presence in Virginia. 
                            The VA LAN works with activists throughout Virginia to organize our communities around 
                            issues-based campaigns that impact our families and our lives. <br/><br/>
                            <a href="https://www.latinainstitute.org/en/virginia">
                                https://www.latinainstitute.org/en/virginia
                            </a>
                        </p>
                        <p>
                            <b>ICE out of RVa</b> <br/><br/>
                            Grassroots organization with the focus of making RVa a safer community for immigrant families 
                            in fear of ICE; work to uplift the work of activists <br/><br/>
                            <a href="https://www.facebook.com/ICEOUTOFRVA/">
                                https://www.facebook.com/ICEOUTOFRVA/
                            </a>
                        </p>
                        <p>
                            <b>Sin Barreras (Charlottesville)</b> <br/><br/>
                            non-profit that focuses on outreach to the immigrant (primarily Hispanic) community, connecting 
                            individuals to services such as workshops in Health, Immigration, Legal affairs, Banking, Education, 
                            and others. They also provide individual services, such as low-cost legal counseling and work one 
                            on one in daily obstacles immigrants face. <br/><br/>
                            <a href="https://sinbarrerascville.com">
                                https://sinbarrerascville.com
                            </a>
                        </p>
                        <p>
                            <b>United We Dream</b> <br/><br/>
                            United We Dream is the largest immigrant youth-led community in the country. We create 
                            welcoming spaces for young people – regardless of immigration status – to support, engage, 
                            and empower them to make their voice heard and win! <br/><br/>
                            <a href="https://unitedwedream.org">
                                https://unitedwedream.org
                            </a>
                        </p>
                     </div>

                     <div className={styles.allyResources}>
                        <p className={styles.allyResourcesText}>
                            <b>Ally Resources</b>
                        </p>
                        <p>
                            <b>Book: “We Are Not Dreamers Undocumented Scholars Theorize Undocumented Life in the United States”</b>  <br/><br/>
                            By centering the voices of undocuemtned scholars, Leisy J/ Abrego and genevieve Negron-Gonzales capture 
                            the complexity of experiences, the intersectionality of identities, and the raw devastation and resilience 
                            of undocumented life. <br/><br/>
                            <a href="https://www.dukeupress.edu/we-are-not-dreamers">
                                https://www.dukeupress.edu/we-are-not-dreamers
                            </a>

                        </p>
                        <p>
                            <b>Book: “America for Americans: A History of Xenophobia in the United States”</b> <br/><br/>
                            Erika Lee examines United States history to demonstrate how Xenophobia is a defining trait of our nation. 
                            She effectively connects the past to contemporary politics. <br/><br/>
                            <a href="https://www.barnesandnoble.com/w/america-for-americans-erika-lee/1130777503?ean=9781541672611">
                                https://www.barnesandnoble.com/w/america-for-americans-erika-lee/1130777503?ean=9781541672611
                            </a>
                        </p>
                        <p>
                            <b>Blog: My Undocumented Life</b> <br/><br/>
                            It provides up-to-date information and resources to undocumented students, their families, 
                            and allies (including educators, counselors, and administrators). <br/><br/>
                            <a href="https://mydocumentedlife.org">
                                https://mydocumentedlife.org
                            </a>
                        </p>
                        <p>
                            <b>Life After College: A Guide for Undocumented Students</b> <br/><br/>
                            This guide includes information, tips, and reouces about life after college for undocumented 
                            students (now undocumented graduates) <br/><br/>
                            <a href="https://mydocumentedlife.org">
                                https://mydocumentedlife.org
                            </a>
                        </p>

                        <p className={styles.allySocialMedia}>
                            <b>Social Media to Follow:</b>
                        </p>
                        <p>
                        @Undocumedia <br/>
                        @UndocuBlack <br/>
                        @FWDus <br/>
                        @NILC_org <br/>
                        @UnitedWeDream <br/>
                        @TP
                        </p>
                     </div>
                </div>

                <div className={styles.contact} id="contact">
                    <p className={styles.icon1}><InstagramIcon sx={{ fontSize: "2vw" }} /> @wmfire__</p>
                    <p className={styles.icon2}><FacebookIcon  sx={{ fontSize: "2vw" }} /> @FightingForImmigrantRightsandEquity</p>
                    <p className={styles.icon3}><EmailIcon sx={{ fontSize: "2vw" }} /> wmfire@email.wm.edu</p>
                    <p className={styles.copyright}>Copyright © {d}, WMFire. All Rights Reserved</p>
                </div>

            </main>

        </div>
    )
}
